# @package callbacks.checkpoint
_target_: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
dirpath: ./checkpoints/
filename: null
monitor: val/loss
verbose: false
save_last: true
save_top_k: 1
save_weights_only: false
mode: min
auto_insert_metric_name: true
every_n_train_steps: null
train_time_interval: null
every_n_epochs: null
save_on_train_epoch_end: true
