_target_: torch.optim.nadam.NAdam
lr: 0.002
betas:
  - 0.9
  - 0.999
eps: 1.0e-08
weight_decay: 0
momentum_decay: 0.004
decoupled_weight_decay: false
foreach: null
capturable: false
differentiable: false
